### ISSUE TITLE
Questions about the hardware configuration of the computer

### ISSUE THREAD

**Issue by Mrhard1999** [wooseoklee4/AP-BSN#9]
Sorry to bother you again, I had a memory issue when I tested a single image.Since my computer only has 8G of running memory, does this experiment require at least 16G and above of running memory?
![BI~Y1 2BX)$KN`_O_EE AGO](https://user-images.githubusercontent.com/56144848/196903541-db0c7a64-abb8-418d-8717-899206f63092.png)

**Comment by wooseoklee4** [comment]
Hi, Mrhard1999.

I used an RTX 2080 TI with 11GB memory, but I think your setting is enough to run inference.
The required memory size depends on the test image size and I think the memory issue is due to the larger image size.
Can you specify the size of the image?

Or I also implemented code for this by cropping a large image into several smaller images and forwarding these smaller images.
See the below code in './src/trainer/base.py'.
![Screenshot from 2022-10-24 17-15-49](https://user-images.githubusercontent.com/14971561/197480702-68c29279-0425-4958-ab64-598863df4fa9.png)

To do this, you should change the configuration file by adding a line: "crop: 512" like down below.
![Screenshot from 2022-10-24 17-23-43](https://user-images.githubusercontent.com/14971561/197481338-f885c21d-d31f-4acd-9da8-adcd3b7c1317.png)
The default setting is 512 size with no overlapping, but I recommend setting a slight overlap to prevent boundary artifacts.

Please let me know If you still have a problem.
Thank you:)

**Comment by Mrhard1999** [comment]
I'm sorry to get back to you so late, the single test was unsuccessful, it is indeed a problem with the size of the image as you said. But I still have a question about two datasets, the DND dataset is a mat file, and it is still mat after training. I didn't understand what your paper said about the 50 pairs of images in DND for testing the model, where is its point of comparison, or do these 50 pairs of pictures need to be taken out of MAT? The second question is appropriate what is the reason why black image blocks are produced when I run the test.py of the SID
![K7J)~RU1~W P181)PNDY~RY](https://user-images.githubusercontent.com/56144848/198171892-9ceef1d7-a12c-4c39-8d5d-8cb6a106619b.png)
D dataset (as shown below)? Looking forward to hearing from you

**Comment by wooseoklee4** [comment]
Hi, Mrhard1999

About the first question, the DND dataset has 50 pairs of images, but they only released noisy images for evaluation.
As the AP-BSN is a self-supervised method, we both trained & tested using these released 50 noisy images.
Also, as you said, the released DND images have .mat format, so we load tensor images from .mat files.
Please refer to the code: './src/datahandler/DND.py'.
In addition, I recommend preparing the dataset using './prep.py' which crops and saves as .png files for training.

And could you specify more details about your test setting?
Did you test the model trained yourself? or use the pre-trained model?
If you are looking for the evaluated images from the pre-trained model, there are evaluated SIDD images for both validation and benchmark.
The links are in the README.md.

Thank you:)

**Comment by Mrhard1999** [comment]
102/5000 
I saw thatevaluated SIDD images for both validation and benchmark.But when i test the model by myself,I haven't changed any parameters. I used a pre-trained model. I would like to know why there would be one black image block after another in the output result.

**Comment by wooseoklee4** [comment]
I checked one more time from the beginning including cloning the project.

I cannot find the error that you mentioned (it works for me like the below image)
![Screenshot from 2022-10-31 17-49-06](https://user-images.githubusercontent.com/14971561/198969456-84543e52-3120-4c63-a50b-4fe5adce94c5.png)

Could you follow the instructions in README.md one more time?
